// voc-files/baza.js

const BAZA_SLOWEK = [
    // Stare słówka
    { lac: "pater", pl: "ojciec" }, { lac: "māter", pl: "matka" }, { lac: "fīlius", pl: "syn" },
    { lac: "servus", pl: "niewolnik" }, { lac: "coquus", pl: "kucharz" }, { lac: "canis", pl: "pies" },
    { lac: "mercātor", pl: "kupiec" }, { lac: "amīcus", pl: "przyjaciel" }, { lac: "argentārius", pl: "bankier" },
    { lac: "ancilla", pl: "niewolnica" }, { lac: "dominus", pl: "pan" }, { lac: "pictor", pl: "malarz" },
    { lac: "tōnsor", pl: "fryzjer" }, { lac: "vēnālīcius", pl: "handlarz niewolników" }, 
    { lac: "senex", pl: "starzec" }, { lac: "leō", pl: "lew" }, { lac: "pāvō", pl: "paw" },
    { lac: "Graecus", pl: "Grek" }, { lac: "tablīnum", pl: "gabinet" },
    { lac: "trīclīnium", pl: "jadalnia" }, { lac: "hortus", pl: "ogród" }, { lac: "culīna", pl: "kuchnia" },
    { lac: "via", pl: "droga" }, { lac: "mēnsa", pl: "stół" }, { lac: "cibus", pl: "jedzenie" },
    { lac: "vīlla", pl: "dom" }, { lac: "pecūnia", pl: "pieniądze" }, { lac: "cēna", pl: "kolacja" },
    { lac: "vīnum", pl: "wino" }, { lac: "forum", pl: "rynek" }, { lac: "iānua", pl: "drzwi" },
    { lac: "pictūra", pl: "obraz" }, 
    { lac: "taberna", pl: "sklep" }, { lac: "sella", pl: "krzesło" }, { lac: "novācula", pl: "brzytwa" },
    { lac: "versus", pl: "wers" }, { lac: "lingua", pl: "język" },
    { lac: "portus", pl: "port" }, { lac: "nāvis", pl: "statek" }, { lac: "cēra", pl: "wosk" },
    { lac: "ānulus", pl: "pierścień" }, { lac: "signum", pl: "znak" }, { lac: "basilica", pl: "sąd" },
    { lac: "saepe", pl: "często" }, { lac: "scrībere", pl: "pisać" }, { lac: "sedēre", pl: "siedzieć" },
    { lac: "bibere", pl: "pić" }, { lac: "semper", pl: "zawsze" }, { lac: "dormīre", pl: "spać" },
    { lac: "intrāre", pl: "wchodzić" }, { lac: "circumspectāre", pl: "rozglądać się" }, { lac: "salīre", pl: "skakać" },
    { lac: "stāre", pl: "stać" }, { lac: "stertere", pl: "chrapać" }, { lac: "lātrāre", pl: "szczekać" },
    { lac: "surgere", pl: "wstawać" }, { lac: "clāmāre", pl: "krzyczeć" }, { lac: "exīre", pl: "wychodzić" },
    { lac: "vīsitāre", pl: "odwiedzać" }, { lac: "salūtāre", pl: "witać" }, { lac: "numerāre", pl: "liczyć" },
    { lac: "respondēre", pl: "odpowiadać" }, { lac: "cantāre", pl: "śpiewać" }, { lac: "coquere", pl: "gotować" },
    { lac: "audīre", pl: "słyszeć" }, { lac: "exspectāre", pl: "czekać" }, { lac: "vituperāre", pl: "ganić" },
    { lac: "portāre", pl: "dźwigać" }, { lac: "gustāre", pl: "próbować" }, { lac: "laudāre", pl: "chwalić" },
    { lac: "dēlectāre", pl: "cieszyć" }, { lac: "vidēre", pl: "widzieć" }, { lac: "cōnsūmere", pl: "spożywać" },
    { lac: "cēnāre", pl: "jeść kolację" }, { lac: "spectāre", pl: "patrzeć" }, { lac: "agere", pl: "działać" },
    { lac: "ambulāre", pl: "chodzić" }, { lac: "venīre", pl: "przychodzić" }, { lac: "pulsāre", pl: "pukać" },
    { lac: "aperīre", pl: "otwierać" }, { lac: "vocāre", pl: "wołać" }, { lac: "dūcere", pl: "prowadzić" },
    { lac: "pingere", pl: "malować" }, { lac: "petere", pl: "atakować" }, { lac: "tenēre", pl: "trzymać" },
    { lac: "verberāre", pl: "bić" }, { lac: "revenīre", pl: "wracać" }, { lac: "tondēre", pl: "strzyc" },
    { lac: "recitāre", pl: "recytować" }, { lac: "rīdēre", pl: "śmiać się" },
    { lac: "fluere", pl: "płynąć" }, { lac: "quaerere", pl: "szukać" }, { lac: "habēre", pl: "mieć" },
    { lac: "emere", pl: "kupować" }, { lac: "discere", pl: "uczyć się" }, { lac: "adesse", pl: "być obecnym" },
    { lac: "imprimere", pl: "odciskać" }, { lac: "trādere", pl: "przekazywać" },
    { lac: "capere", pl: "brać" }, { lac: "currere", pl: "biec" }, { lac: "īrātus", pl: "rozgniewany" },
    { lac: "magnus", pl: "wielki" }, { lac: "laetus", pl: "radosny" }, { lac: "optimus", pl: "najlepszy" },
    { lac: "parātus", pl: "gotowy" }, { lac: "fortis", pl: "silny" }, { lac: "occupātus", pl: "zajęty" },
    { lac: "perterritus", pl: "przerażony" }, { lac: "multus", pl: "liczny" }, { lac: "pulcher", pl: "piękny" },
    { lac: "contentus", pl: "zadowolony" }, { lac: "probus", pl: "uczciwy" },
    { lac: "pestis", pl: "zaraza" }, { lac: "furcifer", pl: "łotr" }, { lac: "salvē", pl: "witaj" },
    { lac: "quoque", pl: "także" }, { lac: "suāviter", pl: "słodko" }, 
    { lac: "magnificē", pl: "wspaniale" }, { lac: "ecce", pl: "oto" }, { lac: "ferōciter", pl: "dziko" },
    { lac: "intentē", pl: "uważnie" }, { lac: "amittere", pl: "zgubić" }, { lac: "sed", pl: "ale" }, { lac: "hodiē", pl: "dzisiaj" },
    { lac: "prope", pl: "blisko" }, { lac: "satis", pl: "dosyć" }, { lac: "ēheu", pl: "och" }, { lac: "ubi?", pl: "gdzie?" },
    
    // Nowe słówka
    { lac: "cūr", pl: "dlaczego" }, { lac: "tamen", pl: "jednak" }, { lac: "fēlēs", pl: "kot" }, { lac: "heri", pl: "wczoraj" }, { lac: "ferus", pl: "dziki" },
    { lac: "turba", pl: "tłum" }, { lac: "ōtiōsus", pl: "nie zajęty" }, { lac: "sanguis", pl: "krew" }, { lac: "cervus", pl: "jeleń" }, { lac: "ferox", pl: "srogi" },
    { lac: "doctus", pl: "uczony" }, { lac: "tenere", pl: "trzymać" }, { lac: "fūstis", pl: "pałka" }, { lac: "gladius", pl: "miecz" }, { lac: "benignus", pl: "dobrotliwy" },
    { lac: "capere", pl: "brać" }, { lac: "secāre", pl: "ciąć" }, { lac: "mox", pl: "wkrótce" }, { lac: "necare", pl: "zabić" }, { lac: "audax", pl: "odważny" },
    { lac: "convincō", pl: "uznaję winnym" }, { lac: "reddere", pl: "oddawać" }, { lac: "ingēns", pl: "ogromny" }, { lac: "interficere", pl: "mordować" },
    { lac: "iūdex", pl: "sędzia" }, { lac: "plaudere", pl: "klaskać" }, { lac: "vexare", pl: "sprawiać kłopot" }, { lac: "postulare", pl: "żądać" },
    { lac: "contendere", pl: "podążać" }, { lac: "clāmor", pl: "hałas" }, { lac: "ōlim", pl: "kiedyś" }, { lac: "terrēre", pl: "przerażać" }, { lac: "ferre", pl: "nosić" },
    { lac: "manere", pl: "zostawać" }, { lac: "nūntius", pl: "zwiastun" }, { lac: "subitō", pl: "nagle" }, { lac: "iterum", pl: "znowu" }, { lac: "spīna", pl: "kolec" },
    { lac: "agricola", pl: "rolnik" }, { lac: "didicit", pl: "nauczył się" }, { lac: "pistor", pl: "piekarz" }, { lac: "umbra", pl: "cień" }, { lac: "ignavus", pl: "tchórzliwy" },
    { lac: "cotīdiē", pl: "codziennie" }, { lac: "nauta", pl: "marynarz" }, { lac: "superare", pl: "pokonywać" }, { lac: "igitur", pl: "więc" }, { lac: "grātiās agō", pl: "dziękuję" },
    { lac: "festinare", pl: "śpieszyć się" }, { lac: "mendāx", pl: "kłamca" }, { lac: "lībertus", pl: "wyzwoleniec" }, { lac: "tandem", pl: "wreszcie" },
    { lac: "iuvenis", pl: "młodzieniec" }, { lac: "testis", pl: "świadek" }, { lac: "omnis", pl: "każdy" }, { lac: "omnes", pl: "wszyscy" }, { lac: "statim", pl: "natychmiast" },
    { lac: "quiētus", pl: "cichy" }, { lac: "accūsās", pl: "oskarżasz" }, { lac: "vendere", pl: "sprzedawać" }, { lac: "gravis", pl: "poważny" }, { lac: "agitāre", pl: "gonić" },
    { lac: "cēlāre", pl: "ukrywać" }, { lac: "euge", pl: "hura" }, { lac: "parvus", pl: "mały" }, { lac: "conspicere", pl: "zauważyć" }, { lac: "notus", pl: "znany" },
	{ lac: "hospes", pl: "gość" }, { lac: "celer", pl: "szybki" }, { lac: "celeriter", pl: "szybko" }, { lac: "nimium", pl: "niezmiernie" }, { lac: "intus", pl: "wewnątrz" },
	{ lac: "quam celerrime", pl: "jak najszybciej" }, { lac: "ruere", pl: "pędzić" }, { lac: "agnoscere", pl: "rozpoznawać" }, { lac: "inspicere", pl: "uważnie oglądać" },
	{ lac: "splendidus", pl: "świetny" }, { lac: "quantī est?", pl: "ile to kosztuje?" }, { lac: "cupere", pl: "bardzo chcieć" }, { lac: "callidus", pl: "mądry" },
	{ lac: "procedere", pl: "posuwać się naprzód" }, { lac: "emittere", pl: "wysyłać" }, { lac: "fundus", pl: "gospodarstwo rolne" }, { lac: "vehementer", pl: "gwałtownie" },
	{ lac: "deinde", pl: "dalej" }, { lac: "plausit", pl: "zaklaskał" }, { lac: "gēns", pl: "ród" }, { lac: "tantum", pl: "tylko" }, { lac: "periculosus", pl: "niebezpieczny" }, 
	{ lac: "rīsit", pl: "zaśmiał się" }, { lac: "cōnsūmpsit", pl: "spożył" }, { lac: "quō?", pl: "dokąd?" }, { lac: "favere", pl: "wspierać" }, { lac: "fautor", pl: "zwolennik" }, 
	{ lac: "conspexit", pl: "zauważył" }, { lac: "videt", pl: "widzi" }, { lac: "vidit", pl: "zobaczył" }, { lac: "caupō", pl: "karczmarz" }, { lac: "civis", pl: "obywatel" },
	{ lac: "venit", pl: "przychodzi" }, { lac: "vēnit", pl: "przyszedł" }, 
	{ lac: "bibit", pl: "pije" }, { lac: "bībit", pl: "wypił" },
];